/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ardian
 */
public class Sistem extends javax.swing.JFrame {

    DefaultTableModel d = new DefaultTableModel();
    static DoubleLLHead data = new DoubleLLHead();
    QueueLO q = new QueueLO();
    int noAntrian = 100;

    /**
     * Creates new form Sistem
     */
    public Sistem() {
        initComponents();
        tabel();
    }

    private void tabel() {

        d.addColumn("No Antrian");
        d.addColumn("Nama");
        d.addColumn("Alamat");
        d.addColumn("Keperluan");
        d.addColumn("Nominal");

        jTable1.setModel(d);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namaTF = new javax.swing.JTextField();
        alamatTF = new javax.swing.JTextField();
        nominalTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tambahB = new javax.swing.JButton();
        hapusB = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cariB = new javax.swing.JButton();
        cariTF = new javax.swing.JTextField();
        keperluan = new javax.swing.JComboBox<>();
        panggilL1B = new javax.swing.JButton();
        panggilL2B = new javax.swing.JButton();
        panggilL3B = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        loket1TA = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        loket3TA = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        loket2TA = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century751 BT", 1, 24)); // NOI18N
        jLabel1.setText("SISTEM ANTRIAN LOKET BANK EXPRESS");

        jLabel2.setText("Nama");

        jLabel3.setText("Alamat");

        jLabel4.setText("Keperluan");

        jLabel5.setText("Nominal");

        namaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTFActionPerformed(evt);
            }
        });
        namaTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                namaTFKeyPressed(evt);
            }
        });

        alamatTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                alamatTFKeyPressed(evt);
            }
        });

        nominalTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nominalTFActionPerformed(evt);
            }
        });
        nominalTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nominalTFKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nominalTFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nominalTFKeyTyped(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        tambahB.setText("ADD");
        tambahB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBActionPerformed(evt);
            }
        });

        hapusB.setText("Hapus/Lewati");
        hapusB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel7.setText("PROSES LOKET");

        jLabel6.setText("Loket 1");

        jLabel8.setText("Loket 2");

        jLabel9.setText("Loket 3");

        cariB.setText("CARI");
        cariB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBActionPerformed(evt);
            }
        });

        cariTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cariTFKeyPressed(evt);
            }
        });

        keperluan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Setor Tunai", "Transfer", "Tarik Tunai", "Pengurusan Kartu ATM", "Pengurusan Kartu Kredit", "Pembuatan Rekening" }));
        keperluan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keperluanActionPerformed(evt);
            }
        });

        panggilL1B.setText("Panggil");
        panggilL1B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panggilL1BActionPerformed(evt);
            }
        });

        panggilL2B.setText("Panggil");
        panggilL2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panggilL2BActionPerformed(evt);
            }
        });

        panggilL3B.setText("Panggil");
        panggilL3B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panggilL3BActionPerformed(evt);
            }
        });

        loket1TA.setEditable(false);
        loket1TA.setColumns(20);
        loket1TA.setRows(5);
        jScrollPane2.setViewportView(loket1TA);

        loket3TA.setEditable(false);
        loket3TA.setColumns(20);
        loket3TA.setRows(5);
        jScrollPane4.setViewportView(loket3TA);

        loket2TA.setEditable(false);
        loket2TA.setColumns(20);
        loket2TA.setRows(5);
        jScrollPane5.setViewportView(loket2TA);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(namaTF, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                            .addComponent(alamatTF)
                                            .addComponent(nominalTF)
                                            .addComponent(keperluan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(tambahB, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(panggilL1B))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(hapusB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cariB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cariTF, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(panggilL2B)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(panggilL3B)
                                        .addGap(78, 78, 78))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(namaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(alamatTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(keperluan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(nominalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahB)
                    .addComponent(hapusB)
                    .addComponent(cariB)
                    .addComponent(cariTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(panggilL2B)
                    .addComponent(panggilL3B)
                    .addComponent(panggilL1B))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keperluanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keperluanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keperluanActionPerformed

    private void panggilL1BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panggilL1BActionPerformed
        // TODO add your handling code here:
        int size = q.size();
        if (size <= 0) {
            JOptionPane.showMessageDialog(null, "ANTRIAN KOSONG! ",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
            loket1TA.setText("");

        } else {
            Object p = q.deQueue();
            String k = p.toString();
            loket1TA.setText(k);
            int index = 0;
            d.removeRow(index);
            index++;
        }
    }//GEN-LAST:event_panggilL1BActionPerformed

    private void tambahBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBActionPerformed
        // TODO add your handling code here:
        if (!namaTF.getText().isEmpty() && !alamatTF.getText().isEmpty()) {
            if (nominalTF.getText().isEmpty()) {
                nominalTF.setText("0");
            }
            String namaKategori = "";
            String nomor = "A" + noAntrian;

            Nasabah b = new Nasabah(nomor, namaTF.getText(), alamatTF.getText(), (String) keperluan.getSelectedItem(), Integer.parseInt(nominalTF.getText()));
            q.enQueue(b);
            Object[] c = new Object[7];
            c[0] = nomor;
            c[1] = namaTF.getText();
            c[2] = alamatTF.getText();
            c[3] = (String) keperluan.getSelectedItem();
            c[4] = nominalTF.getText();

            d.addRow(c);
            JOptionPane.showMessageDialog(null, "Data antrian sudah ditambahkan dengan nomor " + nomor,
                    "Information", JOptionPane.INFORMATION_MESSAGE);
            noAntrian++;
            if (nominalTF.getText().isEmpty()) {
                nominalTF.setText("0");
            }
            namaTF.setText("");
            alamatTF.setText("");
            nominalTF.setText("");
            namaTF.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "Masukkan data terlebih dahulu!",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_tambahBActionPerformed

    private void hapusBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBActionPerformed
        // TODO add your handling code here:
        if (q.size() != 0) {
            q.deQueue();
            d.removeRow(0);
        } else {
            JOptionPane.showMessageDialog(null, "Antrian Kosong!! ",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_hapusBActionPerformed

    private void panggilL2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panggilL2BActionPerformed
        // TODO add your handling code here:
        int size = q.size();
        if (size <= 0) {
            JOptionPane.showMessageDialog(null, "ANTRIAN KOSONG! ",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
            loket2TA.setText("");

        } else {
            Object p = q.deQueue();
            String k = p.toString();
            loket2TA.setText(k);
            int index = 0;
            d.removeRow(index);
            index++;
        }
    }//GEN-LAST:event_panggilL2BActionPerformed

    private void panggilL3BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panggilL3BActionPerformed
        // TODO add your handling code here:
        int size = q.size();
        if (size <= 0) {
            JOptionPane.showMessageDialog(null, "ANTRIAN KOSONG! ",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
            loket3TA.setText("");

        } else {
            Object p = q.deQueue();
            String k = p.toString();
            loket3TA.setText(k);
            int index = 0;
            d.removeRow(index);
            index++;
        }
    }//GEN-LAST:event_panggilL3BActionPerformed

    private void nominalTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nominalTFKeyTyped
        // TODO add your handling code here:
        if (Character.isAlphabetic(evt.getKeyChar())) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Masukan Hanya Angka", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_nominalTFKeyTyped

    private void namaTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaTFKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            alamatTF.requestFocus();
        }
    }//GEN-LAST:event_namaTFKeyPressed

    private void alamatTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alamatTFKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            nominalTF.requestFocus();
        }
    }//GEN-LAST:event_alamatTFKeyPressed

    private void nominalTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nominalTFKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nominalTFKeyReleased

    private void nominalTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nominalTFKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tambahB.doClick();
        }
    }//GEN-LAST:event_nominalTFKeyPressed

    private void cariBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBActionPerformed
        // TODO add your handling code here:
        String key = cariTF.getText();
        Nasabah get = new Nasabah();
        get.setNoAntrian(key);
        if (!cariTF.getText().isEmpty()) {
            if (q.size() != 0) {
                if (q.cari(get) == null) {
                    JOptionPane.showMessageDialog(null, "Nomor " + key + " tidak ditemukan di dalam antrian.",
                            "Information", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Nomor " + key + " ditemukan di dalam antrian.",
                            "Information", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Antrian kosong!",
                        "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Masukkan data terlebih dahulu!",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cariBActionPerformed

    private void nominalTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nominalTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nominalTFActionPerformed

    private void cariTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariTFKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cariB.doClick();
        }
    }//GEN-LAST:event_cariTFKeyPressed

    private void namaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatTF;
    private javax.swing.JButton cariB;
    private javax.swing.JTextField cariTF;
    private javax.swing.JButton hapusB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> keperluan;
    private javax.swing.JTextArea loket1TA;
    private javax.swing.JTextArea loket2TA;
    private javax.swing.JTextArea loket3TA;
    private javax.swing.JTextField namaTF;
    private javax.swing.JTextField nominalTF;
    private javax.swing.JButton panggilL1B;
    private javax.swing.JButton panggilL2B;
    private javax.swing.JButton panggilL3B;
    private javax.swing.JButton tambahB;
    // End of variables declaration//GEN-END:variables
}
